# Generated by Django 2.1.3 on 2018-11-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=32)),
                ('board_str', models.CharField(default=[None, None, None, None, None, None, None, None, None], max_length=54)),
                ('player_human', models.CharField(default='X', max_length=1)),
                ('player_AI', models.CharField(default='O', max_length=1)),
                ('winner', models.CharField(default=None, max_length=4, null=True)),
            ],
        ),
    ]
